routes/web.php
<?php

use App\Http\Controllers\LanguageController;

/*
 * Global Routes
 * Routes that are used between both frontend and backend.
 */

// Switch between the included languages
Route::get('lang/{lang}', [LanguageController::class, 'swap']);

//rute khusus admin
Route::group(['middleware' => 'onlyAdmin'], function(){
  Route::resource('news','NewsController')->except(['index','show']);
});

//rute news khusus index&show (frontend)
Route::resource('news','NewsController')->only(['index','show']);

/*
 * Frontend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
    include_route_files(__DIR__.'/frontend/');
});

/*
 * Backend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    /*
     * These routes need view-backend permission
     * (good if you want to allow more than one group in the backend,
     * then limit the backend features by different roles or permissions)
     *
     * Note: Administrator has all permissions so you do not have to specify the administrator role everywhere.
     * These routes can not be hit if the password is expired
     */
    include_route_files(__DIR__.'/backend/');
});

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    // declare nama tabel
    protected $table = 'news';
    // declare primary key
    protected $primaryKey = 'id';
    // // // set incrementing off
    // // public $incrementing = false;
    // // declare primary key type
    // protected $keyType = 'string';
    // declare blacklist for mass assignable
    protected $guarded = [];

    // relasi dengan table user
    public function user(){
      return $this->belongsTo('App\Models\Auth\User');
    }

}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;

/**
 * Class DashboardController.
 */
class DashboardController extends Controller
{
    /**
     * @return \Illuminate\View\View
     */
    public function index()
    {
        return view('backend.dashboard');
    }
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\Models\News;
use Illuminate\Http\Request;

class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = News::orderBy('created_at','desc')->paginate(8);
        return view('frontend.news.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.news.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $slug = Str_slug($request->title,'-');
        // dd($slug);
        if(News::where('slug',$slug)->first()!=null)
        $slug = $slug.'-'.time();
        // dd($request->konten);
        $data = News::create([
          'user_id' => Auth::user()->id,
          'judul' => $request->title,
          'slug' => $slug,
          'isi' => $request->content,
        ]);
        return redirect(route('news.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  str  $slug
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $new = News::where('slug',$slug)->first();
        if(empty($new))
        abort(404,'message');
        return view('frontend.news.show',compact('new'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $new = News::findOrFail($id);
        return view('backend.news.edit',compact('new'));
        // dd($new);
        // if(empty($new))
        // abort(404,'Something wrong happens with your request:(');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $update = News::findOrFail($id);
        $slug = Str_slug($request->title,'-');
        // dd($slug);
        if(News::where('slug',$slug)->first()!=null)
        $slug = $slug.'-'.time();

        $update->update([
          'user_id' => Auth::user()->id,
          'judul' => $request->title,
          'slug' => $slug,
          'isi' => $request->content,
        ]);

        return redirect(route('news.show',[$slug]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // dd($id);
        $destroy = News::findOrFail($id);
        $destroy->delete();
        return redirect(route('news.index'));
    }
}

resources/views/backend/news/create.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>News</title>
  </head>
  <body>
    <h2>Insert News</h2>
    <form class="" action="{{route('news.store')}}" method="post">
      @csrf
      Author : <br>
      <input type="text" name="author" value="{{Auth::user()->first_name}}" readonly> <br>
      Title : <br>
      <input type="text" name="title" placeholder="Title of The News" value="{{old('title','')}}" maxlength="120"> <br>
      Content : <br>
      <textarea name="content" rows="8" cols="80" placeholder="Content of The News">{{old('content','')}}</textarea>
      <br><br>
      <button type="submit" name="">Publish</button>
    </form>
  </body>
</html>

resources/views/backend/news/edit.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Editing an Article</title>
  </head>
  <body>
    <h2>Revising News</h2>
    <form class="" action="{{route('news.update',[$new->id])}}" method="post">
      @method('PUT')
      @csrf
      Author : <br>
      <input type="text" name="author" value="{{Auth::user()->first_name}}" readonly> <br>
      Title : <br>
      <input type="text" name="title" placeholder="Title of The News" value="{{old('title',$new->judul)}}" maxlength="120"> <br>
      Content : <br>
      <textarea name="content" rows="8" cols="80" placeholder="Content of The News">{!!old('content',$new->isi)!!}</textarea>
      <br><br>
      <button type="submit" name="">Revise</button>
    </form>
  </body>
</html>